{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "c8a26ec6_4b18ce12",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 5
      },
      "lineNbr": 0,
      "author": {
        "id": 1000803
      },
      "writtenOn": "2024-06-04T19:41:44Z",
      "side": 1,
      "message": "Manually setting Verified+1 because the CI failed due to coverity failure caused by new file debugv8p9.c.",
      "revId": "419c5a0cf962828a783daa6d15ff70be8eea0a4b",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    }
  ]
}