{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "b8dcf60d_10f519d0",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 9
      },
      "lineNbr": 0,
      "author": {
        "id": 1000328
      },
      "writtenOn": "2022-06-21T11:04:20Z",
      "side": 1,
      "message": "CI Failure is not related to this patch, so manually provided Verified +1 ",
      "revId": "69a131d894dde9a6570877c7bf181fb60484342d",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    }
  ]
}