{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "dd2aa812_b8fe7390",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1000298
      },
      "writtenOn": "2021-12-03T11:54:04Z",
      "side": 1,
      "message": "CI failures related to Lava environment. I ran some smoke tests on this patch and it works, so setting it to Verified+1",
      "revId": "956d76f69d0c96829784c5a6d16aa79e4e0ecab1",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    }
  ]
}