{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "b0965f46_fbd40c52",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 8
      },
      "lineNbr": 0,
      "author": {
        "id": 1000661
      },
      "writtenOn": "2024-02-22T09:15:17Z",
      "side": 1,
      "message": "The CI fails but the error does not seem related to the code added by these patches. Can someone please take a look and suggest what needs to be done here. Thanks.",
      "revId": "c93ab9336ade1210cb1c325fb8320b270deed878",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    }
  ]
}